### ISSUE TITLE
Feature Request - Other Remote Clients

### ISSUE THREAD

**Issue by RomeoNotaLoka** [linuxserver/docker-webtop#109]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add variable option to disable weburl and internal apache guacamole to allow external remote clients instead.

### Reason for change

I already run guacamole on another container to manage everything. 
I am looking to archive concurrent remote sessions to this container using guacamole.  
I want to allow 2 users to simultaneously connect to it. Using VNC server, which allows multiple users to simultaneously view and control a desktop session. I already try remoting into this container using my other guacamole, but it never connects. I believe the reason is the internal guacamole that is running to allow the web-url to run.

**Comment by thelamer** [comment]
Use this image https://github.com/linuxserver/docker-rdesktop
