### ISSUE TITLE
New OS Request - Kali linux / Parrot os / Black Arch ?

### ISSUE THREAD

**Issue by ArnabDom** [linuxserver/docker-webtop#111]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

offensive security Linux distribution for penetration testing 
Kali Linux / Parrot os / Black Arch would be really good
I hope there will be an offensive Linux distribution Webtop someday

### Reason for change

I wish to have an offensive Linux os for penetration testing that can be accessed as a webtop by hosting anywhere I want

**Comment by thelamer** [comment]
I maintain OSINT images for another project, stuff like parrotOS, Kali, and Tracelabs packages are 10-15 gigs uncompressed post install. We will not be implementing this. 
We have a Debian baseimage most of the tools in ParrotOS/Kali/Tracelabs can simply be installed from their repos.
Same story with blackarch and using the Arch baseimage. 
Our goal with these is to provide a minimum functional desktop, though I encourage you to build whatever you want and please share it with other people: 
https://github.com/linuxserver/docker-baseimage-kasmvnc
https://www.linuxserver.io/blog/webtop-2-0-the-year-of-the-linux-desktop
