### ISSUE TITLE
Can there be a tag for the Awesome window manager?

### ISSUE THREAD

**Issue by SolidRhino** [linuxserver/docker-webtop#14]
## Desired Behavior
Can there be a tag for the Awesome window manager for the webtop docker images?
[Awesome WM](https://awesomewm.org/)

![87d1ebf4-db25-11e6-9eef-f847379afba1](https://user-images.githubusercontent.com/222683/120117059-d776f380-c17a-11eb-82d4-d6feb9f267eb.png)

**Comment by thelamer** [comment]
> ## Desired Behavior
> Can there be a tag for the Awesome window manager for the webtop docker images?
> [Awesome WM](https://awesomewm.org/)
> 
> ![87d1ebf4-db25-11e6-9eef-f847379afba1](https://user-images.githubusercontent.com/222683/120117059-d776f380-c17a-11eb-82d4-d6feb9f267eb.png)

Can you take this for a test drive and see if a base config works OK?
https://hub.docker.com/layers/lsiodev/webtop/alpine-awesome/images/sha256-38445b0b0e01d7b193172eada352feba29d5fc7bdb83d35088e7bc502629d91a?context=explore

I have never used this WM personally so it would be nice to know if there should be any base tweaks for all users or a stock config is ok.

**Comment by thelamer** [comment]
@SolidRhino never heard back on this one.

**Comment by thelamer** [comment]
@SolidRhino last ping then closing this one out. I do not know anyone who uses this Window manager and myself am not comfortable in defining what is a working base layout. 
If a user cannot either confirm the stock config or give some pointers on how it should be configured I am not going to push and advertise the branch.

**Comment by thelamer** [comment]
closing as no one else chimed in
