### ISSUE TITLE
Please add auth for example basic auth

### ISSUE THREAD

**Issue by D4rk4** [linuxserver/docker-webtop#15]
Please add option to set http basic auth

**Comment by thelamer** [comment]
I do not want to maintain authentication logic outside of the keyboard commands that are passed to xrdp.
It is a maintenance and options thing, multiple options exist for web based applications and we as an organization even maintain one: 
https://github.com/linuxserver/docker-swag
When you start to maintain one basic auth method you open pandora's box for directory services and other integrations.
