### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by dtypo** [linuxserver/docker-webtop#16]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Ability to use default user's password (`abc`) for logging into the  container when the screen is locked.
Ability to change the password for the default user (`abc`) via Xterm.
Ability to use `sudo` command via Xterm.

## Current Behavior
Can't login into the container when the screen is locked.
Can't change the password for the default user (`abc`) via Xterm.
Can't use `sudo` command via Xterm.

## Steps to Reproduce
1. add this service to your docker-compose.yml

>  webtop-ubuntu-mate:
        restart: "no"
        image: linuxserver/webtop:ubuntu-mate
        container_name: webtop-ubuntu-mate
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
        security_opt:
            - no-new-privileges:true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /volume3/docker/webtop-ubuntu-mate/config:/config
        ports:
            - 3000:3000
            - "3001:22"
        shm_size: "1gb" #optional

2. give a:

> docker-compose up -d

3. visit the following URL in your browser:

> localhost:3000

4. Open Xterm and give a: 

> passwd

Digit the current password (`abc` is the default password according to the documentation)
![image](https://user-images.githubusercontent.com/40309637/122686749-2ad8e080-d213-11eb-8534-163db72327fe.png)

The terminal gives the following error: 

> passwd: Authentication token manipulation error

5. In Xterm try to give a `sudo apt update`:

![image](https://user-images.githubusercontent.com/40309637/122686916-02051b00-d214-11eb-8555-2c036c4b7c64.png)

The terminal gives the following error: 

> sudo: effective uid is not 0, is /bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

6. Lock the screen:

![image](https://user-images.githubusercontent.com/40309637/122687029-940d2380-d214-11eb-87e5-bd835c9f0082.png)

When trying to unlock the screen using `abc` as password, the system gives `Incorrect password`

![image](https://user-images.githubusercontent.com/40309637/122687086-e2222700-d214-11eb-961e-7c6f1e02b224.png)

## Environment
**OS:** DSM 6.2.4-25556
**CPU architecture:** x86_64 (INTEL Celeron J4125)
**How docker service was installed:**
From Synology official package manager.

**Comment by thelamer** [comment]
Have you tried it without the `--security-opt=no-new-privileges:true` option?

**Comment by thelamer** [comment]
I should not be rhetorical, I know that flag is what is blocking your ability to change the password. Closing.

**Comment by vishalkadam7** [comment]
same issue but I'm using Docker Swarm and it does not support the "privileged" tag

so I'm using

`cap_add:
      - SYS_ADMIN`

but still not working, I'm not sure if this is the right way, can someone guide me
