### ISSUE TITLE
[BUG] file upload does not work

### ISSUE THREAD

**Issue by hubbertsmith** [linuxserver/docker-webtop#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

start docker image --- ubuntu-mate
browser >> localhost:3000
see the desktop
click the left screen icon, will show left VNC menu, will also show top center file cabinet icon, to upload files

I use the top center icon to upload a file
it says "uploading xyz.file"
but does not upload

i tried different files, different directories, confirmed filetransfer worked with docker cp ...

### Expected Behavior

file should upload into selected dir.

### Steps To Reproduce

start docker image --- ubuntu-mate
browser >> localhost:3000
see the desktop
click the left screen icon, will show left VNC menu, will also show top center file cabinet icon, to upload files

I use the top center icon to upload a file
it says "uploading xyz.file"
but does not upload

### Environment

```markdown
- OS: ubuntu 22.04
- How docker service was installed: snap
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -itd \
  --env-file /home/hubbert/webtop/.env \
  -p 3000:3000/tcp  \
  -v /run/snapd.socket:/run/snapd.socket \
  --cap-add=NET_ADMIN \
  --device=/dev/net/tun \
  --network=bridge \
  --mount source=i4voll.3,target=/i4 \
  --restart unless-stopped \
  hs5:latest
```

### Container logs

```bash
docker logs 89cb11ba5566
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

.+....+...+..+................+.........+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+...............+........+....+........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..........+.............+..+....+...+..+....+..+....+...........+....+...+.....+.......+........+.......+...+...+..+.............+...+.....+.....................+.........+.......+...............+..+......+......+.+...+..........................................+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+..+...+.........................+...+.....+.+..............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+..+...+.+......+...+.....+...+...+.+........+..................+....+...........+.........+.+.....+.........+..........+...............+...+........+...+....+...........+...............+....+..+.+........+......+......+...+......+.+...+......+.....+...+......+....+......+..+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
[ls.io-init] done.

Xvnc KasmVNC 1.1.0 - built Jun 17 2023 18:54:12
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

Error: Connection refused
    at PulseAudioContext.<anonymous> (/kclient/node_modules/pulseaudio2/lib/pulse.js:120:36)
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
Error: Access denied
    at /kclient/node_modules/pulseaudio2/lib/pulse.js:133:21
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
Kclient was unable to init audio, it is possible your host lacks support!!!!
```

**Comment by Roxedus** [comment]
Cannot reproduce, uploads just fine. note, we do not support local builds. i have no idea whats done in your hs5 image.

**Comment by hubbertsmith** [comment]
thanks for your reply,
is it possible for you to share a known-good docker script? I will try it
from my end.
thanks!!

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by Roxedus** [comment]
My test is simply `docker run --rm -t --name=test --tmpfs /config:exec -e TZ=${TZ} -e PUID=$(id -u) -e PGID=$(id -g) -p 3000:3000 lscr.io/linuxserver/webtop:ubuntu-mate`

**Comment by j0nnymoe** [comment]
Also, you're using docker on snap. We do not recommend this.

**Comment by hubbertsmith** [comment]
thanks for the reply, sorry if I am pestering
the docker run ... you provided ran without error, localhost:3000 accessed
desktop worked, the file transfer worked ... but all icons were missing,
all of them (including the little black icon"menu" thats always on the
upper left
any ideas

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by Roxedus** [comment]
No. they are also present in my test. Worth checking the browser console

**Comment by hubbertsmith** [comment]
same symptoms in both brave and firefox
I suspect it is due to docker-snap
I am trying on a different system docker-apt, thanks again for the response

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by hubbertsmith** [comment]
yea, I hear you.
on a different system  apt docker.io install ,,, I ran same script
same behavior -- the script ran, localhost:3000 accessed the mate desktop,
the file upload worked, but the menus were absent
same behavior for both brave and firefox

on the same system apt docker.io -- I ran my script, hs5 >> based on
webtop-mate. menus were present, but fileupload silently failed
gotta love computers

thanks so much for your response, I will do what ever you ask from my end
to get this resolved, just ask and I will take care of it



***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by j0nnymoe** [comment]
Providing support for users custom scripts/builds of our containers is not something we support.

**Comment by hubbertsmith** [comment]
no problem, I did not expect you to

focusing on what you DO support. I did this ...
docker run --rm -t --name=test --tmpfs /config:exec -e TZ=${TZ} -e
PUID=$(id -u) -e PGID=$(id -g) -p 3000:3000
lscr.io/linuxserver/webtop:ubuntu-mate
supported right?

the menu icons did not appear -- meaning the little black round icon in
upper right of mate desktops did not appear

this system --- apt install docker.io (not snap)
docker hello world works properly

I am happy to do what ever you ask on my end to troubleshoot (assuming this
is supported, yes?)


***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by j0nnymoe** [comment]
Provide container startup logs please.

**Comment by hubbertsmith** [comment]
thanks again for your help
I got it to work, I can rebuild my image from here.  kindly close the ticket
please LMK what I might do to help you in the future
H

***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>
