### ISSUE TITLE
[BUG] <Ubuntu-mate has no start icon>

### ISSUE THREAD

**Issue by PatelPratikkumar** [linuxserver/docker-webtop#165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I installed Ubuntu-mate, I can't see the start menu icon.
I tried on several machines everywhere it is the same.
I faced this issue with only new version.

### Expected Behavior

When I installed Ubuntu-mate, I can't see the start menu icon.
I tried on several machines everywhere it is the same.
I faced this issue with only new version.

### Steps To Reproduce

Follow the steps of user manual you will get the same issue.

### Environment

```markdown
- OS:
- How docker service was installed:
Using Dockers official installation method.
```

### CPU architecture

x86-64

### Docker creation

```bash
Followed the user manual.
```

### Container logs

```bash
Don't have now
```

**Comment by thelamer** [comment]
I cannot replicate this, try seccomp unconfined and not mounting anything into /config see if that helps. 
![example](https://github.com/linuxserver/docker-webtop/assets/1852688/c703af8f-a63c-463a-9ffd-681c59a092ca)
