### ISSUE TITLE
Cannot route to a public url

### ISSUE THREAD

**Issue by henryxrl** [linuxserver/docker-webtop#17]
I wish to route webtop to my own domain subpath via Caddy. After configuring, all I get is this:
![image](https://user-images.githubusercontent.com/7662954/122849022-b4061b00-d2d8-11eb-8bce-fdc2eb33718a.png)
Any help would be appreciated! Thanks!

**Comment by thelamer** [comment]
The app currently does not support running a subfolder. I'll do this sometime this week: 
https://github.com/linuxserver/gclient/issues/8

**Comment by thelamer** [comment]
Pending rebuilds and doc updates: 
https://github.com/linuxserver/gclient/releases/tag/0.1.1

**Comment by henryxrl** [comment]
Thanks for the update! Looking forward to it!

**Comment by henryxrl** [comment]
I still get the same white screen after specifying the "SUBFOLDER" parameter...

Let's say if my domain name is abc.com and I want the webtop to show up on abc.com/webtop. Does this mean that I need to set the SUBFOLDER parameter as "/webtop"? Or am I doing this wrong?

**Comment by henryxrl** [comment]
It seems only if I route the webtop server to BOTH the abc.com (root) AND abc.com/webtop (subfolder) in the `Caddyfile` will the subfolder (abc.com/webtop) URL work... Disabling the root routing will also make the subfolder routing stop working. Could you please look into this?

**Comment by thelamer** [comment]
Try it with a trailing slash as noted in the documentation.
`/webtop/`

**Comment by henryxrl** [comment]
Yes I also tried adding the trailing slash. But still, it ONLY works if I route to both the root URL and the subfolder URL. Subfder URL won't work if I don't route to the root as well at the same time. :-(

**Comment by thelamer** [comment]
Is there an error in your browser console?

**Comment by thelamer** [comment]
I don't really know caddy. But IE you can use this for Traefik:
```
 docker run --rm -it --name test --label "traefik.http.routers.test.rule=Host(\`localhost\`) && PathPrefix(\`/test\`)" -p 3000:3000 -e SUBFOLDER='/test/' linuxserver/webtop:alpine-kde bash
 ```
 ```
 docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -p 80:80 -p 8080:8080 traefik:v2.4 --api.insecure=true --providers.docker
 ```
 Same basic concept for NGINX.

**Comment by henryxrl** [comment]
![image](https://user-images.githubusercontent.com/7662954/123530859-345bc000-d6cd-11eb-8927-1d3639776b5a.png)

This is everything I got from the browser console. I'll try a few options and see if I can fix it. Thanks!
