### ISSUE TITLE
[BUG] MODs not working while deployed on KASM

### ISSUE THREAD

**Issue by kurotorakun** [linuxserver/docker-webtop#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Details of current implementation:
| | |
|---|---|
| Kasm version | 1.13 |
| Kasm deployment type | on host (no docker) |
| Webtop version used | webtop:ubuntu-xfce |

Docker Run Config Override: 
```
{ 
# <redacted> ...
  "environment": {
    "DOCKER_MODS": "linuxserver/mods:universal-package-install",
    "INSTALL_PACKAGES": "rsync"
  }
} 
``` 
With this configuration, the webtop is deployed but "rsync" package is not installed.

### Expected Behavior

With above configuration, the expected behaviour should be webtop with rsync package installed.

### Steps To Reproduce

1. Install kasm on host
2. Keep default configuration
3. Add Linuxserver repository on Workspace Registry
4. Add "ubuntu xfce" workspace
5. Modify added workspace section "Docker Run Config Override" to include the environment variables declaration on first section.
6. Execute workspace "ubuntu xfce"
7. Open terminal
8. try to use "rsync" or "type rsync"

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: installed following official guide
- Kasm version: 1.13
- Kasm deployment type: on host (no docker)
- Webtop version used: webtop:ubuntu-xfce
```

### CPU architecture

x86-64

### Docker creation

```bash
Docker container creation is handled by kasm.
```

### Container logs

```bash
reviewed logs but they are contaminated with a lot of kasm "noise".
If guided, I can try to provide as much info as possible.
```

**Comment by thelamer** [comment]
When running in Kasm mode these images do not follow lsio init there is a custom init script it uses: 
https://github.com/linuxserver/docker-baseimage-kasmvnc/blob/master/root/kasminit

The container is started in user mode and just runs through this bash logic in Kasm mode. So essentially what you are trying to do is not possible, you would want to modify `/kasminit` inside the container to install packages with sudo.

**Comment by kurotorakun** [comment]
Hi @thelamer , thanks for the answer!
I was pretty sure that it was not a bug, that it was more related to the behavior of the image.

I'm closing the issue.
