### ISSUE TITLE
UI Firefox 

### ISSUE THREAD

**Issue by ksaadDE** [linuxserver/docker-webtop#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sadly, if the UI is opened in Firefox the UI renders buggy. 

For example, you can not close side-panel, once the side panel was opened.  Because the width of the overlapping side-panel is too large, which is not the case in Chrome/Chromium.

I guess it is a bug in KASMVNC but I am not sure about that, please check.

Seemingly, it only works in Chrome or Chromium. At the moment this is not really satisfying. 

### Expected Behavior

It should be possible to close the side-panel, like in Chrome/Chromium. Also the width and height of the UI needs to be fitting to the screen.

### Steps To Reproduce

1. open the UI in your FF browser
2. Click on the side panel 
3. Try to close it..

### Environment

```markdown
- OS: Windows & Linux
- Docker Service was installed via distro pack mgr
```

### CPU architecture

x86-64

### Docker creation

```bash
-
```

### Container logs

```bash
-
```

**Comment by ksaadDE** [comment]
I found a **temporary fix,** by first opening the window tabbed to the side / small and then resizing it to full screen.

The side bar will use the old window size, which seemingly fixes the full width issue and makes it possible to click on the close button. However, this is very uncomfortable. 

It indicates that there is a bug in the JS code that is a wrapper for the KASMVNC stuff. Not sure if that it is true though. I do not have enough time to dig deep.  


https://github.com/linuxserver/docker-webtop/assets/37943746/90aac4a6-f013-455e-bf42-37809c8e6109

**Comment by thelamer** [comment]
This does not seem to be any issue anymore with the new version and current Firefox.
