### ISSUE TITLE
[BUG] <title>ubuntu-mate have not login page?

### ISSUE THREAD

**Issue by leungMr** [linuxserver/docker-webtop#178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Why doesn't ubuntu-mate have a login page? 
Visiting IP:3000 directly leads to the desktop page. 
Even though I changed the password for ABC using `passwd`,  `http://localhost:3000/?login=true` still no default login page appearing?

I can't find what the problem is

### Steps To Reproduce

`http://localhost:3000/?login=true` still no default login page 

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

arm64

### Docker creation

```bash
docker run -d \
  --name=webtop \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Asia/Shanghai \
  -p 3000:3000 \
  -p 3001:3001 \
  -v /path/to/data:/config \
  --shm-size="2gb" \
  --restart unless-stopped \
  lscr.io/linuxserver/webtop:ubuntu-mate
```

### Container logs

```bash
no
```

**Comment by thelamer** [comment]
That behavior is EOL, please read over the options from the baseimage, the old RDP auth has been replaced with a simple basic auth mechanism. 

https://github.com/linuxserver/docker-baseimage-kasmvnc#options
