### ISSUE TITLE
[BUG] Google Chrome not possible to start

### ISSUE THREAD

**Issue by christianmerges** [linuxserver/docker-webtop#179]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I am not able to start chrome. There is a problem with the sandbox:
NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly

but even with --no-sandbox, chrome is not starting.

### Expected Behavior

Chrome should start inside the webtop container

### Steps To Reproduce

sudo -s
apt update && sudo apt install -y wget
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
apt update
apt -y install google-chrome-stable

### Environment

```markdown
Linux cpu1 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### CPU architecture

x86-64

### Docker creation

```bash
The webtop container has the following config:

  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    security_opt:
      - seccomp:unconfined #optional
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - /mnt/docker/webtop/config:/config
      - /mnt/docker/webtop/custom-cont-init.d:/custom-cont-init.d
      - /tmp:/tmp
      - /tmp:/config/.cache
    shm_size: "1gb" #optional
```

### Container logs

```bash
the log is empty
```

**Comment by thelamer** [comment]
I cannot  replicate this, I would start by removing Nvidia and volume stuff. Nvidia GPUs are not supported for GLX stuff, though they would work for backend cuda workloads. https://github.com/linuxserver/docker-baseimage-kasmvnc#dri3-gpu-acceleration

![chrome-ubuntu-webtop](https://github.com/linuxserver/docker-webtop/assets/1852688/87bb7c54-a8f5-4ab5-be3e-bba2c9c39eb6)
