### ISSUE TITLE
Can there be a tag for the Arch Linux with i3wm / i3gaps window manager

### ISSUE THREAD

**Issue by jasek5** [linuxserver/docker-webtop#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Can there be a tag for the [Archlinux](https://archlinux.org) and[ i3-gaps](https://github.com/Airblader/i3)/[i3wm](https://github.com/i3/i3) window manager for the webtop docker images?
(Or at least [arch linux](https://archlinux.org))?

**Comment by j0nnymoe** [comment]
We don't have a Arch baseimage and have no plans to release one as we already have Ubuntu and Alpine baseimages which covers our needs.
