### ISSUE TITLE
Local Keyboard Language not working when set

### ISSUE THREAD

**Issue by benlenau** [linuxserver/docker-webtop#19]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When adding or changing keyboard layout to my local language (danish) local characters aren't working (æ, ø and å).
------------------------------

## Expected Behavior
When adding and selecting Danish keyboard layout it is expected local characters (æ, ø and å) work.

## Current Behavior
ø is on ('*)-key, and æ + å are nowhere to be entered via the keyboard.

Guacamole on-screen keyboard enters the characters correctly but when using attached pc keyboard the keys aren't transfered through the Brave-browser (wherein Danish is also selected as default language). I have tried to remove English layout, restarted, manually selecting danish via top right language-bar, changing through keyboard models, all to no avail. 

Update 25/6-2021: when selecting english keyboard layout on the host pc and danish within the webtop then the EN/US keys are translated to Danish ones within the container. But then the keyboard is unusable on the host os (because the keyboard layout is wrong EN/US).

## Steps to Reproduce
1. Change keyboard layout to Denmark / Danish
2. Use the 3 keys closest to the ENTER/RETURN-key  : " and [
3. And you should be able to get æ, ø and å

![image](https://user-images.githubusercontent.com/70938462/123039712-ec9a1780-d3f2-11eb-9feb-01b9a55041eb.png)

![image](https://user-images.githubusercontent.com/70938462/123040554-40593080-d3f4-11eb-92bc-d6814126db59.png)

## Environment
**OS:** Debian 5.10.40-1~bpo10+1, Docker version 20.10.7, build f0df350, Brave V1.26.67 (June 22, 2021)
**CPU architecture:** x86_64
**How docker service was installed:** official docker repo

## Command used to create docker container (run/create/compose/screenshot)

docker run -d \
  --name=webtop \
  --privileged \
  -e TZ=Europe/Copenhagen \
  -p 192.168.1.2:3000:3000 \
  --shm-size="2gb" \
  --restart unless-stopped \
  ghcr.io/linuxserver/webtop:ubuntu-mate

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 12-prep_xrdp: executing... 
[cont-init.d] 12-prep_xrdp: exited 0.
[cont-init.d] 13-keygen: executing... 

Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to rsakeys.ini

[cont-init.d] 13-keygen: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 55-autostart-config: executing... 
[cont-init.d] 55-autostart-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[guac-init] Auto start not set, application start on login
[services.d] done.
Starting guacamole-lite websocket server
listening on *:3000
[2021-06-23 07:07:51] [Connection 1]  Client connection open
[2021-06-23 07:07:51] [Connection 1]  Opening guacd connection
[2021-06-23 07:07:51] [Connection 1]  guacd connection open
[2021-06-23 07:07:51] [Connection 1]  Selecting connection type: rdp
[2021-06-23 07:07:51] [Connection 1]  Sending opCode: 6.select,3.rdp;
[2021-06-23 07:07:51] [Connection 1]  Sending opCode: 4.size,4.1604,14.1291?undefined,2.96;
[2021-06-23 07:07:51] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
[2021-06-23 07:07:51] [Connection 1]  Sending opCode: 5.video;
[2021-06-23 07:07:51] [Connection 1]  Sending opCode: 5.image;
[2021-06-23 07:07:51] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
[2021-06-23 07:07:51] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.1604,14.1291?undefined,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
xauth:  file .Xauthority does not exist

X.Org X Server 1.20.9
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
Current Operating System: Linux cdfa119bc928 5.10.0-0.bpo.7-amd64 #1 SMP Debian 5.10.40-1~bpo10+1 (2021-06-04) x86_64
Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.10.0-0.bpo.7-amd64 root=UUID=d65e55f6-bd62-4189-bd47-42c968abb8eb ro quiet
Build Date: 08 April 2021  12:29:22PM
xorg-server 2:1.20.9-2ubuntu1.2~20.04.2 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.38.4
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Wed Jun 23 05:07:53 2021
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpProbe: found DRMDevice xorg.conf value [/dev/dri/renderD128]
rdpProbe: found DRI3 xorg.conf value [1]
rdpPreInit:
rdpPreInit: /dev/dri/renderD128 open failed
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7fb817371010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000506e3 bx 0x00100800 cx 0x7ffafbff dx 0xbfebfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpXvInit: depth 24
rdpScreenInit: out
[20210623-05:05:18] [INFO ] starting xrdp with pid 369
[20210623-05:05:18] [INFO ] address [0.0.0.0] port [3389] mode 1
[20210623-05:05:18] [INFO ] listening to port 3389 on 0.0.0.0
[20210623-05:05:18] [INFO ] xrdp_listen_pp done
[20210623-05:07:52] [INFO ] Socket 11: AF_INET6 connection received from ::ffff:127.0.0.1 port 38254
[20210623-05:07:52] [DEBUG] Closed socket 10 (AF_INET6 :: port 3389)
[20210623-05:07:52] [INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
[20210623-05:07:52] [INFO ] Using default X.509 key file: /etc/xrdp/key.pem
[20210623-05:07:52] [DEBUG] TLSv1.3 enabled
[20210623-05:07:52] [DEBUG] TLSv1.2 enabled
[20210623-05:07:52] [DEBUG] Security layer: requested 3, selected 1
ssl_tls_accept: TLS connection accepted
colorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp)
[20210623-05:07:52] [INFO ] connected client computer name: Guacamole RDP
postBeta2ColorDepth 0xca01 (0xca00 4bpp 0xca01 8bpp 0xca02 15bpp 0xca03 16bpp 0xca04 24bpp)
highColorDepth 0x0010 (0x0004 4bpp 0x0008 8bpp 0x000f 15bpp 0x0010 16 bpp 0x0018 24bpp)
supportedColorDepths 0x0007 (0x0001 24bpp 0x0002 16bpp 0x0004 15bpp 0x0008 32bpp)
earlyCapabilityFlags 0x0421 (0x0002 want32)
got client client connection type 0x00000006
xrdp_sec_process_mcs_data_CS_SECURITY:
  client and server support none crypt, using none crypt
[20210623-05:07:52] [INFO ] adding channel item name cliprdr chan_id 1004 flags 0xc0a00000
[20210623-05:07:52] [INFO ] adding channel item name rdpdr chan_id 1005 flags 0xc0800000
[20210623-05:07:52] [INFO ] adding channel item name rdpsnd chan_id 1006 flags 0xc0000000
error unknown xrdp_sec_process_mcs_data tag 0xc006 size 8
error unknown xrdp_sec_process_mcs_data tag 0xc00a size 8
xrdp_sec_out_mcs_data: using no security
xrdp_load_keyboard_layout: keyboard_type [4] keyboard_subtype [0]
xrdp_load_keyboard_layout: model [] variant [] layout [us] options []
[20210623-05:07:52] [INFO ] TLS connection established from ::ffff:127.0.0.1 port 38254: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384
xrdp_caps_process_order: not enough orders supported by client, using painter.
xrdp_caps_process_pointer: client supports new(color) cursor
xrdp_caps_process_glyphcache: support level 2 
xrdp_process_offscreen_bmpcache: support level 1 cache size 7864320 MB cache entries 2000
xrdp_caps_process_surface_cmds:
  cmdFlags 0x00000052
xrdp_caps_process_frame_ack:
  max_unacknowledged_frame_count 2
xrdp_caps_process_confirm_active: not enough orders supported by client, client wants off screen bitmap but offscreen bitmaps disabled
yeah, up_and_running
xrdp_channel_drdynvc_start:
xrdp:xrdp_bitmap [0927235323]: xrdp_bitmap_create: noorders
[20210623-05:07:53] [DEBUG] xrdp_000001a5_wm_login_mode_event_00000001
xrdp:xrdp_mm [0927235354]: xrdp_mm_create: bpp 16 mcs_connection_type 6 jpeg_codec_id 0 v3_codec_id 0 rfx_codec_id 0 h264_codec_id 0
[20210623-05:07:53] [INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
[20210623-05:07:53] [WARN ] local keymap file for 0x00000409 found and doesn't match built in keymap, using local keymap file
xrdp_wm_login_mode_changed: login_mode is 0
in xrdp_wm_init: 
xrdp_wm_init: channel cliprdr channel id 0 is allowed
xrdp_wm_init: channel rdpdr channel id 1 is allowed
xrdp_wm_init: channel rdpsnd channel id 2 is allowed
out xrdp_wm_init: 
xrdp_wm_login_mode_changed: login_mode is 2
[20210623-05:07:53] [DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3350
connecting to sesman ip 127.0.0.1 port 3350
[20210623-05:07:53] [INFO ] xrdp_wm_log_msg: sesman connect ok
sesman connect ok
[20210623-05:07:53] [DEBUG] xrdp_wm_log_msg: sending login info to session manager, please wait...
sending login info to session manager, please wait...
[20210623-05:07:53] [DEBUG] return value from xrdp_mm_connect 0
xrdp_wm_login_mode_changed: login_mode is 3
[20210623-05:07:53] [INFO ] xrdp_wm_log_msg: login successful for display 10
login successful for display 10
loaded module 'libxup.so' ok, interface size 8464, version 4
[20210623-05:07:53] [DEBUG] xrdp_wm_log_msg: started connecting
started connecting
lib_mod_connect: connected tordpCreateScreenResources:
rdpmousePreInit: drv 0x5635ab9c5070 info 0x5635abcc4250, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7fb81754c430
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x5635ab9c6540 info 0x5635abcc6d80, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7fb8175478e0
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 1604 height 1291
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1604 height 1291 mmWidth 424 mmHeight 342
rdpRRGetInfo:
  screen resized to 1604x1291
  RRScreenSizeSet ok 1
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 7
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x5635abcf7750
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1604 height 1291 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0x7fb80c2da000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1604 cy 1291
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpRRGetInfo:
rdpClientConProcessMsgClientInfo:
  got client info bytes 5752
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1604 height 1291
rdpLoadLayout: keylayout 0x00000409 variant  display 10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpRRGetInfo:
rdpRRCrtcGetGamma: 0x5635ab99da00 0x5635abcd0b10 0x5635abcd0f10 0x5635abcd0d10
rdpRRGetInfo:
rdpRRCrtcGetGamma: 0x5635ab99da00 0x5635abcd0b10 0x5635abcd0f10 0x5635abcd0d10
rdpRRGetInfo:
rdpRRCrtcGetGamma: 0x5635ab99da00 0x5635abcd0b10 0x5635abcd0f10 0x5635abcd0d10
rdpRRGetInfo:
rdpRRCrtcGetGamma: 0x5635ab99da00 0x5635abcd0b10 0x5635abcd0f10 0x5635abcd0d10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpmouseCtrl:
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpRRGetInfo:
rdpRRCrtcGetGamma: 0x5635ab99da00 0x5635abcd0b10 0x5635abcd0f10 0x5635abcd0d10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off

**Comment by thelamer** [comment]
Thinking about this a bit, I think the reason the onscreen keyboard works and not your hard wired one is because the on-screen keyboard is hard coded to `en_US`. IE:
https://github.com/linuxserver/gclient/blob/master/public/js/rdp.js#L136
**Can you do me a favor and try to set your system level keymap to English US and see if everything works properly?** 
I am not saying that is a permanent solution, but I just suspect the literal keypresses coming from your keyboard are the hex codes, basically there are two layers of translation happening.

**Comment by benlenau** [comment]
> Thinking about this a bit, I think the reason the onscreen keyboard works and not your hard wired one is because the on-screen keyboard is hard coded to `en_US`. IE:
> https://github.com/linuxserver/gclient/blob/master/public/js/rdp.js#L136
> **Can you do me a favor and try to set your system level keymap to English US and see if everything works properly?**
> I am not saying that is a permanent solution, but I just suspect the literal keypresses coming from your keyboard are the hex codes, basically there are two layers of translation happening.

Yup that worked! I am now able to write my local characters within the container. But the issue now (as you might already know) is that my keyboard now doesn't have the right characters everywhere else *heh*

**Comment by thelamer** [comment]
Good and bad.
The good is we know what is happening, the bad is that I am not 100% on how to tackle this.
In theory you should not have to change the keymap in the container if your browser is sending the hex codes for UTF characters to the containers xrdp session they should just type what you type without changes.
But I assume you allready tried that, the latest tag has font-noto installed so if you fire up a notepad (plums mousepad or leafpad) in an unmodified container it should just enter the characters typed on your desktop side.
I will have some time tomorrow to test.

**Comment by benlenau** [comment]
> Good and bad.
> The good is we know what is happening, the bad is that I am not 100% on how to tackle this.
> In theory you should not have to change the keymap in the container if your browser is sending the hex codes for UTF characters to the containers xrdp session they should just type what you type without changes.
> But I assume you allready tried that, the latest tag has font-noto installed so if you fire up a notepad (plums mousepad or leafpad) in an unmodified container it should just enter the characters typed on your desktop side.
> I will have some time tomorrow to test.

Yeah all (I can think of) combinations have been put through the passes incl. yours (which was excellent, and worked btw), but everything else fails and don't work. Test away and do tell me what else I should try if you figure something else out and I'll do the same :-)

**Comment by thelamer** [comment]
Just a heads up I don't have a solution for this yet and it might take some time. I am trying to prioritize expanding the base images out to new distros and refactoring the whole client app to a modern framework vs 4 year old jquery. 
This will unfortunately take a backseat for the time being, my initial tests of setting the keymap xrdp level did not work so might be kinda complex to support this reliably for the soft keyboard and hardware.

**Comment by benlenau** [comment]
> Just a heads up I don't have a solution for this yet and it might take some time. I am trying to prioritize expanding the base images out to new distros and refactoring the whole client app to a modern framework vs 4 year old jquery.
> This will unfortunately take a backseat for the time being, my initial tests of setting the keymap xrdp level did not work so might be kinda complex to support this reliably for the soft keyboard and hardware.

Check. You do you and I'll check in once in a while to see if fixed :-) You've got a customer here once fixed!

**Comment by thelamer** [comment]
@benlenau please try the latest release with this env variable IE:
`docker run --rm -it -e KEYBOARD=da-dk-qwerty -p 3000:3000 linuxserver/webtop bash`

The other keymaps available are documented here: 
https://github.com/linuxserver/gclient#keyboard-layouts

You do not need to touch the keymap in the container, how this works is that the clientside javascript translates the keydown into an x11 keycode and sends it to the rdesktop client. Xrdp has a series of profiles it can load based on the keymap requested on connect. These are directly written as if the container was localized using your keymap.

Currently this is only built on the alpine xfce container but will waterfall to all of them in a couple days with the new release of gclient @1.0.1. 

I have confirmed functionality by setting my system level keymap to danish and typing in these special characters.

**Comment by benlenau** [comment]
> docker run --rm -it -e KEYBOARD=da-dk-qwerty -p 3000:3000 linuxserver/webtop bash

@thelamer Absolutely brilliant. It now works flawlessly. Thanks a bunch and keep up the good work!
