### ISSUE TITLE
[BUG] Clean webtop install with an empty /config profile does not populate with typical folders like Desktop Downloads Music Pictures etc as it used to

### ISSUE THREAD

**Issue by avoiceofreason** [linuxserver/docker-webtop#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A clean install of webtop:latest only has an ssl folder and some dot folders

### Expected Behavior

A clean install of webtop:latest with an empty /config profile used to create standard folders such as Desktop Downloads Music Pictures etc

I'm pretty sure this was existing webtop behavior at some previous point. My profile from a webtop install in 2023 has all the folders I would expect.

### Steps To Reproduce

1.Delete any existing volume mapped /config profile folders and files
2.Create new webtop:latest docker container
3.Look at /config volume mapping

### Environment

```markdown
- OS:ubuntu 22.04 x86
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run -d \
  --name=webtop2 \
  --security-opt seccomp=unconfined `#optional` \
  -e CUSTOM_USER="user" \
  -e PASSWORD="password" \
  -e PUID=1001 \
  -e PGID=1001 \
  -e TZ=Europe/London \
  -p 8909:3000 \
  -p 8910:3001 \
  -v /var/lib/docker/volume_maps/webtop2/config:/config \
  -v /etc/timezone:/etc/timezone:ro \
  -v /etc/localtime:/etc/localtime:ro \
  --shm-size="3gb" \
  --restart unless-stopped \
  ghcr.io/linuxserver/webtop:latest
```

### Container logs

```bash
N/A
```

**Comment by thelamer** [comment]
Desktop is always created that is part of the XFCE init. 
```
docker run --rm -it -p 3000:3000 linuxserver/webtop bash
cd /config/
955eb8c6b872:/config# ls -l
total 8
drwxr-xr-x 2 abc abc 4096 Jan 17 16:32 Desktop
drwxr-xr-x 2 abc abc 4096 Jan 17 16:32 ssl
```
As far as other default folders those will be created by apps as needed like if you download something in Firefox Downloads will be created. 
I try to do as little as possible in the users home directory and let the Distro/DE do what it wants there.
