### ISSUE TITLE
Local screen mirroring

### ISSUE THREAD

**Issue by dborgesr** [linuxserver/docker-webtop#23]
## Desired Behavior
Display desktop on local screen when one is plugged in as well as being able to use local USB mouse/keyboard

## Current Behavior
No desktop is shown, but an x session can be started and a local desktop is shown, but no keyboard / mouse access.

## Alternatives Considered
I've been able to get a dockerized desktop working locally once using this: https://www.balena.io/blog/running-a-desktop-manager-with-balena, i was able to get it working w/ keyboard and mouse supports, but i haven't been able to combine these two projects!

It would be really incredible to be able to use a screen when available and work locally (raspberry pi 400 keyboard) but connect to webtop when remote.

**Comment by thelamer** [comment]
The entire point of this stack is to run a desktop in a web browser, there are no plans to support X11 forwarding directly.
