### ISSUE TITLE
[FEAT] Environment variable to change default user account name from abc to something else

### ISSUE THREAD

**Issue by cmdpedro** [linuxserver/docker-webtop#254]
### Is this a new feature request?

- [x] I have searched the existing issues

### Wanted change

It would be great if we could change the default user account name from abc to something else via an environment variable.

### Reason for change

While abc works just fine, having a way to change it would allow existing user scripts and tools to work in expected ways.

### Proposed code change

To achieve this, one could possibly adjust the base image and init script.

**Comment by d10sfan** [comment]
I'd also find this useful (for this and rdesktop)

**Comment by drizuid** [comment]
We do not have any interest in doing something like this. `abc` is a standard name, mapped to the specified PUID/PGID in all of our containers.
