### ISSUE TITLE
[FEAT] NixOS images

### ISSUE THREAD

**Issue by nett00n** [linuxserver/docker-webtop#263]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Can you also add NixOS images based on [official NixOS image on docker hub](https://hub.docker.com/r/nixos/nix/)

NixOS is a declarative configured immutable GNU/Linux distributive

### Reason for change

NixOS is cool, btw :)

**Comment by thelamer** [comment]
NixOS is fundamentally incompatible with running inside Docker. 
Different tech but, it is like running Docker in Docker, you need priv to do namespacing and sandboxing. 
For simple programs like CLI stuff the lack of sandboxing is probably fine, but desktop apps would require the user to run the container in privileged mode. 

It is basically a total non starter, and there is nothing upstream can do to make it more compatible as the isolation of packages is their core philosophy.

**Comment by moonpiedumplings** [comment]
Although this isn't a Nixos image, I managed to use the host's Nixos daemon and store for builds and packages.

https://moonpiedumplings.github.io/projects/setting-up-kasm/


This lets you use utilities like nix-shell or nix-build inside a webtop container.

**Comment by thelamer** [comment]
These images are no longer compatible with Kasm, just fyi
