### ISSUE TITLE
[BUG] Tiny bug: The HTML <title> element of lscr.io/linuxserver/webtop:ubuntu-kde has "Alpine KDE" in it

### ISSUE THREAD

**Issue by baxerus** [linuxserver/docker-webtop#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The HTML <title> element of the `lscr.io/linuxserver/webtop:ubuntu-kde` container says "Alpine KDE" what is totally not a very bad thing but still also not right.

### Expected Behavior

The <title> element should have "Ubuntu KDE" in it (that would be my exception).

But generally I would suggest to that the <title> best has something totally neutral like "Webtop" in it (this container is superb 👍, I would encourage you to make your life easy on such stuff, so you can invest your time in more important things. This is a typical thing that will break again and again over time and in the end isn't necessary at all)

### Steps To Reproduce

1. Start a `lscr.io/linuxserver/webtop:ubuntu-kde` container
2. Connect to it
3. Check what is written in the browser tab (or better directly the content of the HTML <title> element)
4. Profit 💰 

### Environment

```markdown
- OS: Everywhere
- How docker service was installed: does not matter
```

### CPU architecture

x86-64

### Docker creation

```bash
-
```

### Container logs

```bash
-
```

**Comment by baxerus** [comment]
I'm talking about the **default** title.

I just learned about the `TITLE` environment variable. With this, I would even stronger saying, that you best simplify your life and set the default to something totally neutral (without OS or Desktop in it) like "Webtop" and done 👍

**Comment by Roxedus** [comment]
Is this a portainer deployed container?
Or is this actually not a x86 deployment, but a arm64 deployment?

**Comment by baxerus** [comment]
You are totally right, it is not `x86` but `arm64`. Sorry for setting the CPU architecture wrong

**Comment by Roxedus** [comment]
Then it makes sense :) https://github.com/linuxserver/docker-webtop/blob/ubuntu-kde/Dockerfile.aarch64#L11

**Comment by baxerus** [comment]
That's an easy fix than.

I still would go for "Webtop" as `default` (so no more issues about that when the next OS / Desktop is added in a hurry 😉)
