### ISSUE TITLE
Request a toggle to screen lock authentication on http://localhost:3000

### ISSUE THREAD

**Issue by BinkyWong** [linuxserver/docker-webtop#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Would like the option to toggle authentication when browsing to:

http://localhost:3000

## Current Behavior

You can only force authentication via:

http://localhost:3000/?login=true

## Alternatives Considered

I tried adding:

/bin/mate-screensaver-command -l

to startwm.sh but it does not execute on startup

**Comment by aptalca** [comment]
If you change the password, auth will be forced. Auto login is only active for the default password

**Comment by BinkyWong** [comment]
Thank you - that works perfect!
