### ISSUE TITLE
Can I disable the feature of downloading files from the webtop container to the local system. So that there is no ingress to my browser/system.

### ISSUE THREAD

**Issue by anish9991** [linuxserver/docker-webtop#30]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

**Comment by thelamer** [comment]
No, this is not a feature of the application, basically the `/files` web path is rendered in as an Iframe and it uses the cloudcmd module (https://cloudcmd.io/). 
https://github.com/linuxserver/gclient/blob/master/app.js#L99
If you are customizing a forking this app the relevant stuff to pull out would be: 
https://github.com/linuxserver/gclient/blob/master/app.js#L10
https://github.com/linuxserver/gclient/blob/master/app.js#L80-L113
https://github.com/linuxserver/gclient/blob/master/public/js/rdp.js#L162-L173
https://github.com/linuxserver/gclient/blob/master/rdp.ejs#L40-L44
