### ISSUE TITLE
version from 2021.10.31 will not fork bash shell

### ISSUE THREAD

**Issue by teachermanalex** [linuxserver/docker-webtop#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I launch the container:
- docker run -p3000:3000 --name webtop  linuxserver/webtop
- then I point my browser at localhost:3000
- I click the terminal icon and it should launch a terminal window with a bash shell

## Current Behavior

The terminal window launches, but it does not contain a running bash shell.
Instead I see an terminal window with a popup containing error message "Failed to execute child process bash: failed to Fdwalk: Operation not permitted.  

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**. Docker desktop for mac on MacOS Catalina 10.15.7
**CPU architecture:** x86_64
**How docker service was installed:**

Docker desktop for mac v 4.1.1
Docker engine 20.10.8
I'm not sure how I installed it originally, but I am on the latest version

## Command used to create docker container (run/create/compose/screenshot)

- docker run -p3000:3000 --name webtop  linuxserver/webtop

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 13-keygen: executing...

Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to rsakeys.ini

Generating a RSA private key
.........................................................................................+++++
...........................................................+++++
writing new private key to '/etc/xrdp/key.pem'
-----
[cont-init.d] 13-keygen: exited 0.
[cont-init.d] 30-config: executing...
stat: cannot stat '/config/.config': No such file or directory
[cont-init.d] 30-config: exited 0.
[cont-init.d] 55-autostart-config: executing...
[cont-init.d] 55-autostart-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[guac-init] Auto start not set, application start on login
[services.d] done.
starting sesman in foreground...
Filename:                     /etc/xrdp/sesman.ini
Global configuration:
    ListenAddress:            127.0.0.1
    ListenPort:               3350
    EnableUserWindowManager:  1
    UserWindowManager:        startwm.sh
    DefaultWindowManager:     /etc/xrdp/startwm.sh
    ReconnectScript:          /etc/xrdp/reconnectwm.sh
    AuthFilePath:             disabled
Session configuration:
    MaxSessions:              50
    X11DisplayOffset:         10
    KillDisconnected:         0
    IdleTimeLimit:            0
    DisconnectedTimeLimit:    0
    Policy:                   0
Security configuration:
    AllowRootLogin:           1
    MaxLoginRetry:            4
    AlwaysGroupCheck:         0
    RestrictOutboundClipboard: 0
    TSUsersGroup:             (not defined)
    TSAdminsGroup:            (not defined)
Xorg parameters:
    Parameter 00              Xorg
    Parameter 01              -config
    Parameter 02              xrdp/xorg.conf
    Parameter 03              -noreset
guacd[360]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
guacd[360]: INFO:	Listening on host 0.0.0.0, port 4822
    Parameter 04              logging configuration:
Starting guacamole-lite websocket server
listening on *:3000
(node:352) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[2021-11-03 20:22:54] [Connection 1]  Client connection open
[2021-11-03 20:22:54] [Connection 1]  Opening guacd connection
[2021-11-03 20:22:54] [Connection 1]  guacd connection open
[2021-11-03 20:22:54] [Connection 1]  Selecting connection type: rdp
[2021-11-03 20:22:54] [Connection 1]  Sending opCode: 6.select,3.rdp;
guacd[360]: INFO:	Creating new client for protocol "rdp"
guacd[360]: INFO:	Connection ID is "$fe00bbd5-81f5-4083-b632-79d130235660"
[2021-11-03 20:22:54] [Connection 1]  Sending opCode: 4.size,4.1659,13.808?undefined,2.96;
[2021-11-03 20:22:54] [Connection 1]  Sending opCode: 5.audio,9.audio/L16;
[2021-11-03 20:22:54] [Connection 1]  Sending opCode: 5.video;
[2021-11-03 20:22:54] [Connection 1]  Sending opCode: 5.image;
[2021-11-03 20:22:54] [Connection 1]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
[2021-11-03 20:22:54] [Connection 1]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.1659,13.808?undefined,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
guacd[401]: INFO:	Security mode: Negotiate (ANY)
guacd[401]: INFO:	Resize method: none
guacd[401]: INFO:	User "@3d43aeb4-c387-4bdd-b182-c33a3b7b3fc3" joined connection "$fe00bbd5-81f5-4083-b632-79d130235660" (1 users now present)
guacd[401]: INFO:	Loading keymap "base"
guacd[401]: INFO:	Loading keymap "en-us-qwerty"
xauth:  file .Xauthority does not exist

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: Linux Alpine Linux
Current Operating System: Linux 730d7c55f3ee 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64
Kernel command line: earlyprintk=serial page_poison=1 vsyscall=emulate panic=1 nospec_store_bypass_disable noibrs noibpb no_stf_barrier mitigations=off console=ttyS0 console=ttyS1  vpnkit.connect=connect://2/1999
Build Date: 14 April 2021  08:27:11AM

Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: ".xorgxrdp.10.log", Time: Wed Nov  3 20:22:55 2021
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7fad24bd22a0
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x000906ed bx 0x05010800 cx 0xfeda7a17 dx 0x9f8bfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpXvInit: depth 24
rdpScreenInit: out
rdpCreateScreenResources:
rdpmousePreInit: drv 0x7fad2510d830 info 0x7fad24b71b50, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7fad24dad3b1
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x7fad2510d8d0 info 0x7fad24b71bf0, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7fad24da88a8
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 1656 height 808
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1656 height 808 mmWidth 438 mmHeight 214
rdpRRGetInfo:
  screen resized to 1656x808
  RRScreenSizeSet ok 1
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 10
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x7fad24d931f0
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1656 height 808 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 0 shmemptr 0x7fad2417f000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1656 cy 808
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
Global configuration:
rdpRRGetInfo:
	LogFile:       /var/log/xrdp.log
	LogLevel:      [INFO ]
	ConsoleLevel:  <disabled>
	SyslogLevel:   [INFO ]
ssl_tls_accept: TLS connection accepted
xrdp:xrdp_bitmap [3883403065]: xrdp_bitmap_create: noorders
xrdp:xrdp_mm [3883403069]: xrdp_mm_create: bpp 16 mcs_connection_type 6 jpeg_codec_id 0 v3_codec_id 0 rfx_codec_id 0 h264_codec_id 0
xrdp_wm_login_mode_changed: login_mode is 0
in xrdp_wm_init:
xrdp_wm_init: channel cliprdr channel id 0 is allowed
xrdp_wm_init: channel rdpdr channel id 1 is allowed
xrdp_wm_init: channel rdpsnd channel id 2 is allowed
out xrdp_wm_init:
xrdp_wm_login_mode_changed: login_mode is 2
connecting to sesman ip 127.0.0.1 port 3350
sesman connect ok
sending login info to session manager, please wait...
xrdp_wm_login_mode_changed: login_mode is 3
login successful for display 10
loaded module 'libxup.so' ok, interface size 10280, version 4
started connecting
lib_mod_connect: connected to Xserver (Xorg or X11rdp) sck 19
connected ok
lib_mod_process_message: type 2 len 0
lib_send_client_info:fuse: device not found, try 'modprobe fuse' first
rdpClientConProcessMsgClientInfo:
  got client info bytes 7056
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1656 height 808
rdpLoadLayout: keylayout 0x00000409 variant  display 10
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
guacd[401]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[401]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[401]: INFO:	Connected to RDPDR 1.12 as client 0xc687ddb8
guacd[401]: INFO:	RDPDR user logged on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpRRGetInfo:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off

**Comment by thelamer** [comment]
It's in the readme, use podman or pass `--security-opt seccomp=unconfined` Docker still has not fixed this. 
https://github.com/docker/for-linux/issues/1262
