### ISSUE TITLE
Make one for Kali Linux

### ISSUE THREAD

**Issue by haxoa** [linuxserver/docker-webtop#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I would like to see an option to play on Kali Linux, as that has been my OS for a long time.
## Current Behavior

There is no Kali Linux option.
## Alternatives Considered

I have tried using dog.wtf's method of running Kali Linux in the web browser, however, it is very slow and has downtime.

**Comment by thelamer** [comment]
Kali is debian based, we already have Ubuntu. You are able to install all of the penetration testing tools in Kali in Ubuntu. 
You also need to understand that what makes Kali Kali is the special firmware and kernel modules aimed at scanning and penetration. Docker cannot do anything Kernel or syscall level, that is on your host setup. Keep in mind Docker is not a VM.

**Comment by fonsixx** [comment]
> Kali is debian based, we already have Ubuntu. You are able to install all of the penetration testing tools in Kali in Ubuntu. 
> 
> You also need to understand that what makes Kali Kali is the special firmware and kernel modules aimed at scanning and penetration. Docker cannot do anything Kernel or syscall level, that is on your host setup. Keep in mind Docker is not a VM. 

Ubuntu is very slow though, and when I run it on Google Cloud, it oftentimes crashes and I have to reload my website, and all of my current files are wiped. How do I fix this?

**Comment by thelamer** [comment]
This is not a support platform, we use github for bugs and feature requests. 
A webtop is no meant to be created and destroyed like other docker images, you want to use restart and stop not compose commands to redeploy and update. Anything in your home directory will survive but programs/some settings installed will be lost.
