### ISSUE TITLE
firefox crash on playing youtube videos on arm64

### ISSUE THREAD

**Issue by timnis** [linuxserver/docker-webtop#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Able to watch videos from youtube with firefox

## Current Behavior
When trying to watch video from youtube it crash firefox tabs.

I also upgraded packges inside webtop (with sudo apk upgrade) and also tested with firefox (removed esr version first), but same issue. 

Then I tested with linuxserver/libreoffice container and installed firefox to that and it worked.  No firefox crash on youtube videos. So problem is not an host or docker service.

## Steps to Reproduce
1. start firefox, goto youtube and try to watch video

## Environment
**OS:** Oracle Linux Server 7.9
**CPU architecture:** arm64
**How docker service was installed:**
sudo yum install docker-engine

## Command used to create docker container (run/create/compose/screenshot)
sudo docker create \
  --name=webtop \
  -e TZ=Europe/London `# Your local timezone` \
  -e PUID=1000 `# Application user ID` \
  -e PGID=1000 `# Application group ID` \
  -v /host/path/to/var/run/docker.sock:/var/run/docker.sock `# Docker Socket on the system, if you want to use Docker in the container` \
  -v /host/path/to/config:/config `# Application home directory` \
  -p 3000:3000/tcp `# Web Desktop GUI` \
  --restart unless-stopped \
  linuxserver/webtop

**Comment by thelamer** [comment]
`--shm-size= | We set this to 1 gig to prevent modern web browsers from crashing` check out the readme
