### ISSUE TITLE
Arch webtop; abc is not in the sudoers file.  This incident will be reported.

### ISSUE THREAD

**Issue by eliranwong** [linuxserver/docker-webtop#38]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I cannot use sudo command in Arch webtop container.  Error message:

abc is not in the sudoers file.  This incident will be reported.

It seems there is no way for me to login as root to change the sudoers file.  

abc is not a sudoer

root's password is not abc

------------------------------

## Expected Behavior

I expect I can use sudo command on Arch webtop, as I can on Ubuntu, Fedora, Alpine webtops.

## Current Behavior

sudo command can be used only on Ubuntu, Fedora, Alpine webtops but not Arch webtop

## Steps to Reproduce

1. Run a container of Arch webtop
2. Open terminal
3. use sudo command
4. error message: abc is not in the sudoers file.  This incident will be reported.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-baseimage-rdesktop/commit/b914f4e6b16ebbc0b1dc2d63b99b7166c69e5461
This is going to take some time to build and waterfall (probably not until tomorrow) to all the images. In arch it looks like if you use GUID=1000 the existing users group messes with the passwordless sudo set for the abc group. 
By setting it to the user here it works regardless of conflicting gids.

**Comment by eliranwong** [comment]
> GUID=1000

Yes, I did set GUID=1000

> By setting it to the user here it works regardless of conflicting gids.

I am afraid I do not understand this last sentence.  May I ask what is "setting it to the user"?  Does it mean setting the username as the Linux host, changing "abc" to my Linux host username?

many thanks for your help.

**Comment by thelamer** [comment]
I was not providing support, I was pointing out the bug. All the images have built now pull a new one.
