### ISSUE TITLE
Howto prevent abc user password from been reset after container update?

### ISSUE THREAD

**Issue by 3x3cut0r** [linuxserver/docker-webtop#40]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
abc user password should not been reset after container update (caused from watchtower for example)

## Current Behavior
abc user password has been reset to "abc" after the docker container was updated

## Steps to Reproduce

1. change user password via console (docker exec -it webtop passwd abc)
2. delete docker stack with docker-webtop (using portainer)
3. deploy new docker-webtop stack (using portainer, with AUTO_LOGIN=false)
4. password is resetted to "abc"

## Environment
**OS:** Debian 11
**CPU architecture:** x86_64
**How docker service was installed:** docker rootless

**Comment by j0nnymoe** [comment]
The read me tells you not to update these containers like you would any other container. https://github.com/linuxserver/docker-webtop#application-setup
