### ISSUE TITLE
Alpine-KDE Container starts with incorrect ports

### ISSUE THREAD

**Issue by vdisp** [linuxserver/docker-webtop#45]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Based on the Docker compose file container should start with port 5000 exposed.
From the https://fleet.linuxserver.io/image?name=linuxserver/webtop Docker Compose details:
`    ports:
      - 5000:5000/tcp # Web Desktop GUI
`
Currently I have AdGuard Home running on port 3000 and another container running on port 4000 so I changed the port for webtop to 5000.

## Current Behavior
When attempting to connect to `http://yourhost:5000/` I receive an error stating:

> Unable to connect
>Firefox can’t establish a connection to the server at 192.168.1.100:5000.

Image details show the following:
`
EXPOSE | 3000/tcp,    3389/tcp
`
Log file shows `listening on *:3000`

Container details show `Port configuration | 0.0.0.0:5000,  5000/tcp,  :::5000,  5000/tcp`

## Steps to Reproduce

1. Ran the Docker compose file
2. Container starts but not using the designated port/s

## Environment
**Debian 11**
**CPU architecture:** x86_64
**How docker service was installed:**

Debian CLI `apt install docker`

## Command used to create docker container (run/create/compose/screenshot)

---
version: "2.1"
services:
  webtop:
    image: linuxserver/webtop:alpine-kde
    container_name: webtop
    restart: unless-stopped
    environment:
      - TZ=America/Phoenix  # Your local timezone
      - PUID=1000 # Application user ID
      - PGID=1000 # Application group ID
    devices:
      - /dev/dri:/dev/dri  # optional for Linux hosts
    volumes: 
      - /mnt/storage/.appdata/docker/webtop:/config # Application home directory
    ports:
      - 5000:5000/tcp # Web Desktop GUI
    env_file: # only necessary if you want to change the password, see .env file
      - .env

## Docker logs

Via Portainer:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 13-keygen: executing... 

Generating 2048 bit rsa key...

ssl_gen_key_xrdp1 ok

saving to rsakeys.ini

Generating a RSA private key
....+++++
......................................+++++
writing new private key to '/etc/xrdp/key.pem'
-----
[cont-init.d] 13-keygen: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 1.
[cont-init.d] 50-gid-video: executing... 
**** creating video group videotnmy with id 107 ****
**** adding /dev/dri/renderD128 to video group videotnmy with id 107 ****
**** creating video group videosajd with id 44 ****
**** adding /dev/dri/card0 to video group videosajd with id 44 ****
[cont-init.d] 50-gid-video: exited 0.
[cont-init.d] 55-autostart-config: executing... 
[cont-init.d] 55-autostart-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
xrdp-sesman[457]: [INFO ] starting xrdp-sesman with pid 457
[guac-init] Auto start not set, application start on login
[services.d] done.
guacd[469]: INFO:	Guacamole proxy daemon (guacd) version 1.1.0 started
xrdp[460]: [INFO ] starting xrdp with pid 460
guacd[469]: INFO:	Listening on host 0.0.0.0, port 4822
xrdp[460]: [INFO ] address [0.0.0.0] port [3389] mode 1
xrdp[460]: [INFO ] listening to port 3389 on 0.0.0.0
xrdp[460]: [INFO ] xrdp_listen_pp done
Starting guacamole-lite websocket server
listening on *:3000

**Comment by aptalca** [comment]
Fleet shows `3000:3000`, which is the correct port mapping. If you want to change it to 5000, it needs to be `5000:3000`

**Comment by vdisp** [comment]
Ahhh, OK, got it.

That worked...Thanks!!!
