### ISSUE TITLE
Add systemd support

### ISSUE THREAD

**Issue by tunbk1002** [linuxserver/docker-webtop#50]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

configuring system with systemd is not possible

## Current Behavior

```sh
timedatectl list-timezones
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by Roxedus** [comment]
We have no plans on switching the init system for our containers.
