### ISSUE TITLE
Why isn't there a version with the Gnome desktop environment?

### ISSUE THREAD

**Issue by xabru** [linuxserver/docker-webtop#94]
I remember that I asked the same thing 2 years ago and they deleted my question a few days later, is there a technical problem with gnome and the Docker container?

**Comment by bolavefasfas** [comment]
Yes I also am waiting for gnome flavor for a long time

**Comment by LotusCloud** [comment]
> I remember that I asked the same thing 2 years ago and they deleted my question a few days later, is there a technical problem with gnome and the Docker container?

Check out this 
https://hub.docker.com/repository/docker/lotuscloud/ubuntu

**Comment by aptalca** [comment]
@LotusCloud please don't link to random docker hub images

Users: Please don't run random docker hub images. You don't know what's running in there (could be a crypto miner, could be much worse)

**Comment by Niko-La** [comment]
would be nice but maybe gnome and unity are too resource intensive currently?

has anyone able to to get ubuntu look using mate mutiny working?

**Comment by thelamer** [comment]
Gnome is heavily connected to DBUS and Systemd which do not play nice inside docker, I know it is plausible as other images have hacked it into a Docker container, but seems like it would be a constant fight to keep it working considering we automatically update all of these containers. Not something I have time for.
