### ISSUE TITLE
Error Missing X server or $DISPLAY on brave on Ubuntu mate

### ISSUE THREAD

**Issue by glardz98** [linuxserver/docker-webtop#96]
i run a container webtop ubuntu mate on host debian 11 but when i run Brave in ubuntu mate i have this message:

```
root@0b3bd7aba275:/config# /bin/brave-browser [6194:6194:1116/002939.784984:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
root@0b3bd7aba275:/config# /bin/brave-browser --no-sandbox [6220:6220:1116/002954.827870:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY [6220:6220:1116/002954.827917:ERROR:env.cc(255)] The platform failed to initialize. Exiting. /bin/brave-browser: line 48: 6220 Trace/breakpoint trap "$HERE/brave" "$@" root@0b3bd7aba275:/config#
```

i install Gnome on debian but same issue.

when i did docker run i mounted tmp file with all X0,X1,X10,X1024,X1025 on ubuntu mate and when i run brave i have same error.

`docker run -d -v "/tmp/.X11-unix/:/tmp/.X11-unix/" -e PUID=1001 -e PGID=1001 -p 3003:3000 --shm-size="1gb" lscr.io/linuxserver/webtop:ubuntu-mate`
do you know the problem ?

**Comment by thelamer** [comment]
All chromium browsers need to run with `--no-sandbox` to run in a docker container you had it right with the second command. 
I cannot replicate this on Focal or Jammy, I just installed from their repo and ran it: 

![brave](https://user-images.githubusercontent.com/1852688/207687399-53cab0b7-0151-476b-bee3-2ca52f8723e9.png)

You are running these commands inside the webtop from the mate terminal right?
